env:
  browser: true
  es2021: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

extends:
  - eslint:recommended
  - airbnb-base

plugins:
  - import

rules:
  # максимально отпускаем стиль, чтобы не мешал
  no-console: off
  no-use-before-define: off
  no-param-reassign: off
  import/no-unresolved:
    - error
    - ignore:
        - on-change
