env:
  browser: true
  es2021: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - import

rules:
  semi:
    - error
    - never
  arrow-parens: off
  brace-style: off
  no-console: off
  no-use-before-define: off
  no-param-reassign: off
  import/no-unresolved:
    - error
    - ignore:
        - on-change
